In [2]:
import pandas as pd

In [3]:
sfusd_df = pd.read_csv( '../../lottery/merged/sfusd-school-id-mapping.csv' )
sfusd_df.head()

   school_id               school_name
0        441  Access SFUSD: Bay Street
1        442     Access SFUSD: The Arc
2        413                  Alamo ES
3        420               Alvarado ES
4        431                  Aptos MS

In [5]:
doe_df = pd.read_csv( '../../enrollment/raw/pubschls.txt', sep = '\t' )
doe_df.head()

,CDSCode,NCESDist,NCESSchool,StatusType,County,District,School,Street,StreetAbr,City,...,Virtual,Magnet,YearRoundYN,FederalDFCDistrictID,Latitude,Longitude,AdmFName,AdmLName,LastUpDate,Multilingual
0,1100170000000,0691051,No Data,Active,Alameda,Alameda County Office of Education,No Data,313 West Winton Avenue,313 West Winton Ave.,Hayward,...,No Data,No Data,No Data,No Data,37.658212,-122.09713,Alysse,Castro,03/08/2023,No Data
1,1100170109835,0691051,10546,Closed,Alameda,Alameda County Office of Education,FAME Public Charter,"39899 Balentine Drive, Suite 335","39899 Balentine Dr., Ste. 335",Newark,...,P,N,N,No Data,37.521436,-121.99391,No Data,No Data,09/01/2015,No Data
2,1100170112607,0691051,10947,Active,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,1515 Webster Street,1515 Webster St.,Oakland,...,N,N,N,0601614,37.804520,-122.26815,Elizabeth,Raji-Greg,05/20/2024,N
3,1100170114363,0691051,12013,Active,Alameda,Alameda County Office of Education,American Indian Public Charter School II,171 12th Street,171 12th St.,Oakland,...,N,N,N,0601880,37.800368,-122.26548,Marco,Menendez,09/08/2025,N
4,1100170118489,0691051,12283,Closed,Alameda,Alameda County Office of Education,Aspire California College Preparatory Academy,2125 Jefferson Avenue,2125 Jefferson Ave.,Berkeley,...,N,N,N,No Data,37.868991,-122.27844,No Data,No Data,07/01/2015,No Data